import type { School } from './types';

export const schools: School[] = [
  {
    id: 'uoft',
    name: 'University of Toronto',
    abbr: 'UofT',
    color: '#002A5C',
    program: '3-Year MD',
    programLen: 3,
    mcatStatus: 'required',
    gpa: {
      min: '3.6 (UG) · 3.3 (Grad)',
      competitive: '3.9+',
      note: 'OMSAS scale. Best 3 years used (lowest year dropped if 4+ years completed). Graduate applicants have a lower threshold of 3.3.',
    },
    mcat: {
      min: '125 per section (one 124 allowed)',
      competitive: '515+ total',
      note: 'MCAT used only as a pass/fail threshold — NOT assessed competitively in ranking. Scores from the past 5 years accepted. Must be written before application deadline.',
    },
    prereqs: [
      'Minimum 3 years of full-time undergraduate study',
      '2 full course equivalents (FCEs) in life sciences',
      '1 FCE in humanities, social sciences, or languages',
    ],
    website: 'https://applymd.utoronto.ca/academic-requirements',
    seats: '~259',
  },
  {
    id: 'mcmaster',
    name: 'McMaster University',
    abbr: 'Mac',
    color: '#7A003C',
    program: '3-Year MD',
    programLen: 3,
    mcatStatus: 'cars',
    gpa: {
      min: '3.0',
      competitive: '3.87+',
      note: 'OMSAS scale. GPA accounts for 32% of pre-interview score. GPA is NOT rounded — exact decimal is used. Graduate students receive a 1–4% bonus.',
    },
    mcat: {
      min: 'CARS section: 123 minimum',
      competitive: 'CARS: 129 (class average)',
      note: 'CARS section ONLY is reviewed — all other MCAT sections are completely ignored. CARS is 32% of pre-interview score (equal to GPA and Casper).',
    },
    prereqs: [
      'Minimum 3 years of undergraduate study (30 half-year credits / 15 FCEs)',
      'No specific course prerequisites',
      'Casper test required (32% of pre-interview score)',
      'No degree-type restriction — any undergraduate program accepted',
    ],
    website: 'https://ugme.healthsci.mcmaster.ca/admissions/',
    seats: '~203',
  },
  {
    id: 'western',
    name: 'Western University',
    abbr: 'Schulich',
    color: '#4F2683',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'required',
    gpa: {
      min: '3.7 in each of 2 undergrad years',
      competitive: '3.9+',
      note: 'OMSAS scale. The 3.7 minimum must be met in 2 separate individual undergraduate years (not cumulative average). Thresholds are reviewed annually.',
    },
    mcat: {
      min: '127 C/P · 127 CARS · 127 B/B · 126 P/S (2024–25)',
      competitive: '512+ total',
      note: 'Section minimums reset each year based on applicant pool competitiveness. Pathway stream applicants: 125 per section minimum. Scores within 5 years accepted.',
    },
    prereqs: [
      'Minimum 3 years of a 4-year accredited undergraduate degree',
      'No specific prerequisite courses required',
      'Broad background in arts, humanities, and sciences is recommended',
    ],
    website: 'https://www.schulich.uwo.ca/med-dent-admissions/medicine/admission-requirements.html',
    seats: '~171',
  },
  {
    id: 'queens',
    name: "Queen's University",
    abbr: "Queen's",
    color: '#B10D28',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'required',
    gpa: {
      min: '3.0',
      competitive: '3.85 (class avg)',
      note: '2025 cycle introduced QARS: applicants meeting all minimum thresholds (GPA + MCAT + Casper) are entered into a randomized lottery for MMI invitations.',
    },
    mcat: {
      min: '500 total · 125 in each section',
      competitive: '512+',
      note: 'All 4 section minimums must be met in a single test sitting. Casper is also required; threshold determined annually and not publicly disclosed.',
    },
    prereqs: [
      '90 credit-hours (15 FCEs) completed by end of application cycle',
      'No strict prerequisite courses',
      'May apply during 3rd year of undergraduate study',
      'Casper test required',
    ],
    website: 'https://meds.queensu.ca/academics/mdprogram/admissions',
    seats: '~100',
  },
  {
    id: 'uottawa',
    name: 'University of Ottawa',
    abbr: 'uOttawa',
    color: '#8F001A',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'no',
    gpa: {
      min: '3.5',
      competitive: '3.93 (class median)',
      note: 'OMSAS scale. Based on the most recent 3 years of full-time undergraduate study (5 courses per term). Offers both English and French streams.',
    },
    mcat: {
      min: 'Not required',
      competitive: 'N/A',
      note: 'uOttawa does NOT require the MCAT. One of very few Canadian MD programs with no standardized test requirement — evaluation is fully holistic.',
    },
    prereqs: [
      '3 years of full-time undergraduate study (5 courses per term each year)',
      'No specific prerequisite courses required',
      'Solid science foundation highly recommended',
      'Available in both English and French streams',
    ],
    website: 'https://www.uottawa.ca/faculty-medicine/undergraduate/application-process',
    seats: '~164',
  },
  {
    id: 'nosm',
    name: 'NOSM University',
    abbr: 'NOSM',
    color: '#1a7a4a',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'no',
    gpa: {
      min: '3.0',
      competitive: '3.76 (class avg)',
      note: 'GPA calculated from last 2 years of full-time undergraduate study. Holistic admissions process — community ties and Northern Ontario connection heavily weighted.',
    },
    mcat: {
      min: 'Not required',
      competitive: 'N/A',
      note: 'NOSM does NOT require the MCAT, and submitted MCAT scores are NOT reviewed. Strong emphasis on connection to Northern Ontario or rural/remote communities.',
    },
    prereqs: [
      '3 years (90 credits) of full-time undergraduate study at an accredited university',
      'No mandatory prerequisite courses',
      'Science majors: 12 units of arts, social sciences, or humanities recommended',
      'Arts/humanities majors: 12 units of science recommended',
      'Connection to Northern Ontario or rural community strongly valued',
    ],
    website: 'https://www.nosm.ca/nosm-university-admissions-learner-recruitment/ume-program-md-degree-admissions/',
    seats: '~64',
  },
];
