import type { School } from './types';

export const schools: School[] = [
  {
    id: 'uoft',
    name: 'University of Toronto',
    abbr: 'UofT',
    color: '#002A5C',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'required',
    gpa: {
      min: '3.6 (UG) · 3.3 (Grad)',
      competitive: '3.94',
      note: 'OMSAS scale. Cumulative GPA (all years) is used. Graduate applicants have a lower minimum threshold of 3.3. Mean accepted GPA was 3.94 in the 2025 cycle.',
    },
    mcat: {
      min: '125 per section (one 124 allowed)',
      competitive: '515+ total',
      note: 'MCAT used only as a pass/fail threshold. NOT assessed competitively in ranking. Scores from the past 5 years accepted. Must be written before application deadline.',
    },
    prereqs: [
      'Minimum 3 years of full-time undergraduate study (eligible to apply fall of 3rd year if all requirements met)',
      '2 full course equivalents (FCEs) in life sciences',
      '1 FCE in humanities, social sciences, or languages',
      '2 brief personal essays (250 words or less each)',
      'OMSAS Autobiographical Sketch (ABS) required',
    ],
    website: 'https://applymd.utoronto.ca/academic-requirements',
    seats: '303',
  },
  {
    id: 'mcmaster',
    name: 'McMaster University',
    abbr: 'Mac',
    color: '#7A003C',
    program: '3-Year MD',
    programLen: 3,
    mcatStatus: 'cars',
    gpa: {
      min: '3.0',
      competitive: '3.92',
      note: 'OMSAS scale. GPA accounts for 32% of pre-interview score. GPA is NOT rounded; exact decimal is used. Graduate bonus: +1% (Masters), +4% (PhD). Class of 2028 mean GPA was 3.92.',
    },
    mcat: {
      min: 'CARS section: 123 minimum',
      competitive: 'CARS: 129',
      note: 'CARS section ONLY is reviewed; all other MCAT sections are completely ignored. CARS is 32% of pre-interview score (equal to GPA and CASPer). Class of 2028 mean CARS was 129.',
    },
    prereqs: [
      'Minimum 3 years of undergraduate study (30 half-year credits / 15 FCEs); eligible to apply fall of 3rd year if requirements met',
      'No specific course prerequisites',
      'No degree-type restriction; any undergraduate program accepted',
      'CASPer test required (32% of pre-interview score)',
    ],
    website: 'https://ugme.healthsci.mcmaster.ca/admissions/',
    seats: '217',
  },
  {
    id: 'western',
    name: 'Western University',
    abbr: 'Schulich',
    color: '#4F2683',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'required',
    gpa: {
      min: '3.7 in each of 2 undergrad years',
      competitive: '3.96 / 3.91',
      note: 'OMSAS scale. The 3.7 minimum must be met in each of 2 separate undergraduate years (best 2 years taken). A qualifying year requires at least 5 FCEs (30 credit hours), of which at least 3 FCEs (18 credit hours) must be at or above the year level of study, and a maximum of 1 pass/fail FCE. Thresholds are reviewed annually. Class of 2029 mean best 2 years were 3.96 and 3.91.',
    },
    mcat: {
      min: '126 per section (125 for pathway)',
      competitive: '513',
      note: 'Section minimums reset each year based on applicant pool competitiveness. Scores within 5 years accepted. Class of 2029 mean MCAT was 513.',
    },
    prereqs: [
      'Minimum 3 years of a 4-year accredited undergraduate degree (eligible to apply fall of 3rd year if requirements met)',
      'No specific prerequisite courses required',
      'Autobiographical Sketch (ABS) required',
      'KIRA Talent online assessment required',
    ],
    website: 'https://www.schulich.uwo.ca/med-dent-admissions/medicine/admission-requirements.html',
    seats: '190',
  },
  {
    id: 'queens',
    name: "Queen's University",
    abbr: "Queen's",
    color: '#B10D28',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'required',
    gpa: {
      min: '3.0',
      competitive: '3.75',
      note: 'QARS system: applicants meeting all minimum thresholds (GPA + MCAT + CASPer) are entered into a randomized lottery for MMI invitations. No preferred degree. Class of 2029 mean GPA was 3.75.',
    },
    mcat: {
      min: '500 total · 125 in each section',
      competitive: '513',
      note: 'All 4 section minimums must be met in a single test sitting. CASPer is also required; threshold determined annually and not publicly disclosed. Class of 2029 mean MCAT was 513.',
    },
    prereqs: [
      '90 credit-hours (15 FCEs) completed by end of application cycle',
      'No strict prerequisite courses',
      'Eligible to apply fall of 3rd year if requirements met',
      'CASPer test required',
    ],
    website: 'https://meds.queensu.ca/academics/mdprogram/admissions',
    seats: '138',
  },
  {
    id: 'uottawa',
    name: 'University of Ottawa',
    abbr: 'uOttawa',
    color: '#8F001A',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'no',
    gpa: {
      min: '3.5',
      competitive: '3.93',
      note: 'OMSAS scale. Based on the most recent 3 years of full-time undergraduate study (5 courses per term). Offers both English and French streams. 2024 mean GPA was 3.93.',
    },
    mcat: {
      min: 'Not required',
      competitive: 'N/A',
      note: 'uOttawa does NOT require the MCAT. One of very few Canadian MD programs with no standardized test requirement.',
    },
    prereqs: [
      '3 years of full-time undergraduate study (5 courses per term each year); eligible to apply fall of 3rd year if requirements met',
      '6 units in humanities or social sciences',
      '6 units in biology',
      '3 units in organic chemistry',
      '3 units in general chemistry',
      '3 units in biochemistry',
      '3 units in statistics',
      '2 laboratory courses',
      'CASPer test required',
      'Top 3 activities highlighted from 18 total ABS entries',
      'Available in both English and French streams',
    ],
    website: 'https://www.uottawa.ca/faculty-medicine/undergraduate/application-process',
    seats: '187',
  },
  {
    id: 'tmu',
    name: 'Toronto Metropolitan University',
    abbr: 'TMU',
    color: '#C9960C',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'no',
    gpa: {
      min: '3.5',
      competitive: '3.8',
      note: 'OMSAS scale. Holistic review with strong emphasis on equity, diversity, and lived experience. Completed undergraduate degree required before starting the program. Class of 2029 mean GPA was 3.8.',
    },
    mcat: {
      min: 'Not required',
      competitive: 'N/A',
      note: 'TMU does NOT require the MCAT or CASPer. Non-academic assessment uses KIRA Talent (asynchronous video/written) followed by an MMI.',
    },
    prereqs: [
      'Completed undergraduate degree required (full degree; cannot apply in 2nd or 3rd year)',
      'No specific prerequisite courses required',
      'No preferred degree program',
      '3 short essay questions required',
      'Regional connection to Peel Region and surrounding areas is valued',
      'KIRA Talent online assessment required (6 timed video/written questions)',
    ],
    website: 'https://www.torontomu.ca/school-of-medicine/programs/md/md-admissions/before-you-apply/admission-requirements/',
    seats: '94',
  },
  {
    id: 'nosm',
    name: 'NOSM University',
    abbr: 'NOSM',
    color: '#1a7a4a',
    program: '4-Year MD',
    programLen: 4,
    mcatStatus: 'no',
    gpa: {
      min: '3.0',
      competitive: '3.76',
      note: 'Pre-interview score is a combination of GPA and context score (rural/Northern Ontario background). Cumulative GPA (all years) is used. Mean GPA of admitted students was 3.76.',
    },
    mcat: {
      min: 'Not required',
      competitive: 'N/A',
      note: 'NOSM does NOT require the MCAT, and submitted MCAT scores are NOT reviewed. Strong emphasis on connection to Northern Ontario or rural/remote communities.',
    },
    prereqs: [
      '3 years (90 credits) of full-time undergraduate study at an accredited university',
      'No mandatory prerequisite courses',
      'Science majors: 2 FCEs (4 semester courses) in arts, social sciences, or humanities recommended',
      'Arts/humanities majors: 2 FCEs (4 semester courses) in science recommended',
      'Connection to Northern Ontario or rural community strongly valued (50% of score)',
    ],
    website: 'https://www.nosm.ca/nosm-university-admissions-learner-recruitment/ume-program-md-degree-admissions/',
    seats: '88',
  },
];
